### ISSUE TITLE
file w serum information

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/flu_seqneut_H3N2_2023-2024#3]
@ckikawa I think their should be a CSV listing each serum and relevant information about it. Eg, the identifier for the sera used in this project, age or year of birth, description, vaccination, etc. Any information that is used about specific sera to make plots for the paper should come out of this CSV.

**Comment by huddlej** [comment]
I just wanted to upvote this request! 😄 Thank you both!

**Comment by jbloom** [comment]
Actually, just looking at this, the files were added but not linked in the part of the README that mentions the sera samples. They should be linked in README too.
